from __future__ import annotations

from typing import Protocol

from app.domain.models import BudgetCategory, BudgetSubCategory


class BudgetRepository(Protocol):
    def list_categories_for_user(self, user_id: str) -> list[BudgetCategory]: ...

    def create_category_for_user(self, user_id: str, category: BudgetCategory) -> BudgetCategory: ...

    def update_category_for_user(self, user_id: str, category_id: str, name: str, color_hex: str, icon: str, is_essential: bool) -> BudgetCategory: ...

    def delete_category_for_user(self, user_id: str, category_id: str) -> None: ...

    def create_sub_category_for_user(self, user_id: str, sub_category: BudgetSubCategory) -> BudgetSubCategory: ...

    def update_sub_category_for_user(self, user_id: str, sub_category_id: str, name: str, monthly_amount_usd: int) -> BudgetSubCategory: ...

    def delete_sub_category_for_user(self, user_id: str, sub_category_id: str) -> None: ...
