import { useMemo, useState } from 'react';
import { FinanceMoneyCellInput, FinanceMoneyCellValue, FinanceTable, FinanceTableHeaderCell } from '../components/FinanceTable';
import { ApiError } from '../api/httpClient';
import type { MortgageSchedule } from '../domain/netWorth';
import type { NetWorthRepository } from '../domain/netWorthRepository';
const fmt=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format;
const now=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`};
const label=(m:string,i:number)=>{const [y,n]=m.split('-').map(Number);return new Date(y,n-1+i,1).toLocaleDateString('en-US',{month:'short',year:'numeric'})};
const num=(v:string)=>Number(v.replace(/[$,]/g,''));
const compactExtraOverrides=(overrides:Record<string,number>,defaultValue:number)=>{let effectiveValue=defaultValue;return Object.fromEntries(Object.entries(overrides).sort(([left],[right])=>Number(left.split(':')[1])-Number(right.split(':')[1])).filter(([,value])=>{if(value===effectiveValue)return false;effectiveValue=value;return true}))};
const compactPrincipalOverrides=(overrides:Record<string,number>,schedule:Pick<MortgageSchedule,'startingOutstandingMortgage'|'annualInterestRate'|'monthlyPrincipalPayment'|'monthlyAdditionalPrincipalPayment'>,month:string,extraOverrides:Record<string,number>)=>{let balance=schedule.startingOutstandingMortgage,effectiveExtra=schedule.monthlyAdditionalPrincipalPayment;const payment=schedule.monthlyPrincipalPayment+schedule.startingOutstandingMortgage*schedule.annualInterestRate/12,compact:Record<string,number>={};for(let i=0;i<1200&&balance>0;i++){const key=`${month}:${i}`,expectedPrincipal=Math.max(0,payment-balance*schedule.annualInterestRate/12),override=overrides[key],principal=Math.min(balance,override??expectedPrincipal);if(override!==undefined&&Math.abs(override-expectedPrincipal)>0.005)compact[key]=override;if(extraOverrides[key]!==undefined)effectiveExtra=extraOverrides[key];const extra=Math.min(balance-principal,effectiveExtra);balance=Math.max(0,balance-principal-extra)}return compact};
type Inputs=Pick<MortgageSchedule,'houseValue'|'startingOutstandingMortgage'|'annualInterestRate'|'monthlyPrincipalPayment'|'monthlyAdditionalPrincipalPayment'>;
type Props={initial?:MortgageSchedule|null;repository:Pick<NetWorthRepository,'putMortgageSchedule'>;onSaved:(v:MortgageSchedule)=>void};
export function MortgageSchedulePanel({initial,repository,onSaved}:Props){
 const [d,setD]=useState({houseValue:String(initial?.houseValue??''),annualInterestRate:String(initial?.annualInterestRate??''),startingOutstandingMortgage:String(initial?.startingOutstandingMortgage??''),monthlyPrincipalPayment:String(initial?.monthlyPrincipalPayment??''),monthlyAdditionalPrincipalPayment:String(initial?.monthlyAdditionalPrincipalPayment??'')});
 const [month,setMonth]=useState(initial?.scheduleStartMonth??now()),[all,setAll]=useState(false),[po,setPo]=useState<Record<string,number>>(initial?.principalOverrides??{}),[eo,setEo]=useState<Record<string,number>>(initial?.extraPrincipalOverrides??{}),[err,setErr]=useState<string|null>(null),[saving,setSaving]=useState(false);
 const p=useMemo(()=>Object.fromEntries(Object.entries(d).map(([k,v])=>[k,Number(v)])) as unknown as Inputs,[d]);
 const rows=useMemo(()=>{if(Object.values(p).some(v=>!Number.isFinite(v)||v<0))return[];let bal=p.startingOutstandingMortgage,prior=p.houseValue-bal;const scheduledPayment=p.monthlyPrincipalPayment+p.startingOutstandingMortgage*p.annualInterestRate/12;const out=[] as Array<{i:number;m:string;principal:number;extra:number;balance:number;equity:number;pct:number;diff:number}>;let effectiveExtra=p.monthlyAdditionalPrincipalPayment;for(let i=0;i<1200&&bal>0;i++){const key=`${month}:${i}`,principal=Math.min(bal,po[key]??Math.max(0,scheduledPayment-bal*p.annualInterestRate/12));if(eo[key]!==undefined)effectiveExtra=eo[key];const extra=Math.min(bal-principal,effectiveExtra);bal=Math.max(0,bal-principal-extra);const equity=p.houseValue-bal;out.push({i,m:label(month,i),principal,extra,balance:bal,equity,pct:p.houseValue?equity/p.houseValue*100:0,diff:p.houseValue?(equity-prior)/p.houseValue*100:0});prior=equity}return out},[p,month,po,eo]);
 const save=async()=>{if(Object.values(p).some(v=>!Number.isFinite(v)||v<0)){setErr('Enter finite, nonnegative values.');return}setSaving(true);setErr(null);const v:MortgageSchedule={...p,scheduleStartMonth:month,principalOverrides:compactPrincipalOverrides(po,p,month,eo),extraPrincipalOverrides:compactExtraOverrides(eo,p.monthlyAdditionalPrincipalPayment)};try{const saved=await repository.putMortgageSchedule!(v);onSaved(saved.mortgageSchedule??v)}catch(error){setErr(error instanceof ApiError ? error.message : 'Unable to save mortgage schedule. Your edits are still here; try again.')}finally{setSaving(false)}};
 const update=(key:keyof typeof d,v:string)=>{setD({...d,[key]:v});setErr(null)};
 const updatePrincipal=(index:number,value:string)=>{const nextValue=num(value);if(!Number.isFinite(nextValue))return;setPo({...po,[`${month}:${index}`]:nextValue});if(index===0)update('monthlyPrincipalPayment',String(nextValue))};
 const updateExtraPrincipal=(index:number,value:string)=>{const nextValue=num(value);if(Number.isFinite(nextValue))setEo({...eo,[`${month}:${index}`]:nextValue})};

 const shown=all?rows:rows.slice(0,12);
 const tableRows=shown.length?shown:[{i:0,m:label(month,0),principal:p.monthlyPrincipalPayment||0,extra:p.monthlyAdditionalPrincipalPayment||0,balance:p.startingOutstandingMortgage||0,equity:(p.houseValue||0)-(p.startingOutstandingMortgage||0),pct:0,diff:0}];
 return <section className="source-form" aria-labelledby="mortgage-schedule-heading"><div className="page-header-text" style={{marginBottom:20}}><h2 id="mortgage-schedule-heading">Mortgage Schedule</h2><p>Home value and interest rate are configured in Configuration. Seed the schedule in the sticky first row.</p></div>{err&&<p className="form-error" role="alert">{err}</p>}<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:24}}><h3>Projection</h3><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/> Show all payments</label></div><FinanceTable aria-label="Mortgage schedule" wrapperStyle={{marginTop:12}}><thead><tr>{['Payment','Month','Equity','Principal','Extra Principal','Balance','Equity %','Equity Diff'].map(x=><FinanceTableHeaderCell key={x}>{x}</FinanceTableHeaderCell>)}</tr></thead><tbody>{tableRows.map(r=><tr key={r.i} className={r.i === 0 ? 'mortgage-start-row' : undefined}><td>{r.i+1}</td><td>{r.i===0?<input aria-label="Schedule start month" type="month" value={month} onChange={e=>setMonth(e.target.value)}/>:r.m}</td><td><FinanceMoneyCellValue value={r.equity} formatValue={fmt}/></td><td><FinanceMoneyCellInput aria-label={`Principal ${r.m}`} value={r.principal} formatValue={fmt} focusId={`principal-${r.i}`} nextFocusId={r.i<tableRows.length-1?`principal-${r.i+1}`:undefined} onValueChange={value=>updatePrincipal(r.i,value)}/></td><td><FinanceMoneyCellInput aria-label={`Extra principal ${r.m}`} value={r.extra} formatValue={fmt} focusId={`extra-principal-${r.i}`} nextFocusId={r.i<tableRows.length-1?`extra-principal-${r.i+1}`:undefined} fillDownLabel={`Auto-populate Extra Principal from ${r.m} down`} onFillDown={value=>updateExtraPrincipal(r.i,value)} onValueChange={value=>updateExtraPrincipal(r.i,value)}/></td><td>{r.i===0?<FinanceMoneyCellInput aria-label="Starting balance" value={p.startingOutstandingMortgage} formatValue={fmt} onValueChange={v=>{const n=num(v);if(Number.isFinite(n))update('startingOutstandingMortgage',String(n))}}/>:<FinanceMoneyCellValue value={r.balance} formatValue={fmt}/>}</td><td>{r.pct.toFixed(2)}%</td><td>{r.diff.toFixed(2)}%</td></tr>)}</tbody></FinanceTable><div style={{display:'flex',justifyContent:'flex-end',marginTop:20}}><button className="primary-action" type="button" disabled={saving} onClick={()=>void save()}>{saving?'Saving...':'Save mortgage schedule'}</button></div></section>
}
